### ISSUE TITLE
Input issue

### ISSUE THREAD

**Issue by Pederytter** [donmbelembe/vue-dragscroll#1]
Hey there

Thanks for taking your time to make this plugin, I was quite happy to see there were a vue version of this.

I do have some trouble using input fields, if the input element is inside the html tag with the v-dragscroll tag. I made a short codepen so you can see the problem live:

https://codepen.io/anon/pen/KXXmLw

Not sure what to look after to debug this.

**Comment by donmbelembe** [comment]
Actually When you use the directive with the argument  **:nochilddrag**, It while dragscroll only when you hold click on the parent itself like in this exemple http://asvd.github.io/jailed/demos/web/process/ 
But I understand your case let me see what improvement i can do for this plugin

**Comment by Pederytter** [comment]
hmm, I can't seem to figure out how :nochilddrag works. It just keep crashing my vue.

Possible you can modify my codepen example so that :nochilddrag works?

**Comment by donmbelembe** [comment]
when you click this http://asvd.github.io/jailed/demos/web/process/ ,
On the box when you try to dragscroll by **holding on the text inside the box** it will not scroll (_it will select the text instead_), the dragscroll works only when you hold inside the box but not hover the child element

**Comment by donmbelembe** [comment]
so in your case the the **div with the blue background** is a child element of the dragscroll,  that why It's crashing your vue when you set the argument :nochilddrag

**Comment by donmbelembe** [comment]
check https://codepen.io/anon/pen/pWWrxO
I've removed the <div class="background">...</div> and moved the form somewhere in the parent element in other to cause an overflow.
with the argument  :nochilddrag set as you can see, you can dragscroll by holding down anywhere inside the box except the input field.
but if you remove the  :nochilddrag, even if you hold down the input field it is dragscrolling

**Comment by Pederytter** [comment]
Ohh I see.

Thanks a lot for the explanation. It really helped alot with the codepen example.

Still have a few problems with getting it to work right for my project, but that's beacause the child elements has a margin which needs to be draggable. Unfortuneatly it doesnt inherit all the way up to the main element which got the v-dragscroll:nochilddrag tag.

You can see what I'm trying to accomplish here:
http://prntscr.com/gso8pr

I will probably make a codepen later on which showcase the issue better in the future.

**Comment by donmbelembe** [comment]
OK I saw you image, i trying to think what solution for your project.
you are trying to do something like trello??

**Comment by Pederytter** [comment]
Sort of. It's a lot more aimed at students, with more functions for them.

But for the "scrum" version is your library a key component, to navigate around in the project. The whole grey area is supposed to be dragable to move around, where right now you can't drag around in the spaces between the columns and the top unfortuneatly.

**Comment by donmbelembe** [comment]
hey you can use the :firstchilddrag argument on this will support you initial structure. check the last example in the docs
