### ISSUE TITLE
Failed to execute 'elementFromPoint' on 'Document

### ISSUE THREAD

**Issue by endeffects** [donmbelembe/vue-dragscroll#10]
While running your directive in the chrome touch simulator an error is thrown in the directives.js file:
line: let isEl = document.elementFromPoint(e.pageX - window.pageXOffset, e.pageY - window.pageYOffset) === el
error: directives.js?3e88:16 Uncaught TypeError: Failed to execute 'elementFromPoint' on 'Document': The provided double value is non-finite.
    at HTMLDivElement.el.md (directives.js?3e88:16)
    at HTMLDivElement.el.md (directives.js?3e88:16)

**Comment by donmbelembe** [comment]
Hey did you solve this problem yet ? Just coming from hollidays

**Comment by diff-dennis** [comment]
I also have the same problem. This probably also prevents using this plugin with a touch device. If I want to scroll a page with such an element e.g. on an iPad, I cannot vertically scroll the whole page when I swipe inside of the dragscroll-enabled element.

**Comment by celeryclub** [comment]
This is due to `touchstart` events not always having a `pageX` property. I've opened a PR to address this.

**Comment by donmbelembe** [comment]
Thank you @celeryclub  for submitting a PR, let me check it
