### ISSUE TITLE
Latest version not working for me (nuxt project)

### ISSUE THREAD

**Issue by dataexcess** [donmbelembe/vue-dragscroll#108]
Hello,

I tried using the vue-dragscroll in a new nuxt project and it didn't work. I went mad because it used to work on an older nuxt project that I did. I tried to reduce my project to the most basic setup but nothing worked. In the end I realised I could just use the same package version as the older project and that did the trick. 

So right now I'm pinned to version 2.1.3 which made it work in my new project. Sorry I cannot give more info but I thought I would let you know.

**Comment by donmbelembe** [comment]
Hello, did you get an error? what version of nuxt did you use ?

**Comment by dataexcess** [comment]
No errors, it just does not work. 
nuxt version: 2.15.7

**Comment by donmbelembe** [comment]
version 4 of this package drop support for Vue 2, 
you can still install the version 3 on vue-dragscroll to work with vue2

It was stated in the docs

![image](https://user-images.githubusercontent.com/10473277/194833698-66f5e259-ad4c-4913-bfc6-f2569132b9df.png)

**Comment by dataexcess** [comment]
Ooooooh okok!
My bad 🤣
Thank you!
