### ISSUE TITLE
Not working for me on Vue 3 - Need help

### ISSUE THREAD

**Issue by vishytk** [donmbelembe/vue-dragscroll#109]
Vue3+Vite+TS+Tailwind CSS

https://stackblitz.com/edit/vitejs-vite-esgad5?file=src%2FApp.vue

**Comment by vishytk** [comment]
Is there demo code available somewhere ?

**Comment by donmbelembe** [comment]
here is the demo code
https://github.com/donmbelembe/vue-dragscroll-docs
