### ISSUE TITLE
Nuxt3 update?

### ISSUE THREAD

**Issue by feelthemoon** [donmbelembe/vue-dragscroll#112]
any updates for Nuxt3?

**Comment by taylott** [comment]
not sure if this will help your or not but I added this at /plugins/dragscroll.js and I can use the directive in nuxt 3 with "v-dragscroll"

`import VueDragscroll from "vue-dragscroll";

export default defineNuxtPlugin(({vueApp}) => {
  vueApp.use(VueDragscroll);
});`

**Comment by feelthemoon** [comment]
> not sure if this will help your or not but I added this at /plugins/dragscroll.js and I can use the directive in nuxt 3 with "v-dragscroll"
> 
> ```
> import VueDragscroll from "vue-dragscroll";
> 
> export default defineNuxtPlugin(({vueApp}) => {
>   vueApp.use(VueDragscroll);
> });
> ```

Ok, no problem, I've dealt with it

**Comment by yanghoxom** [comment]
@feelthemoon can you share abit about it?
I also work on nuxt 3, and nothing happens when I add v-dragscroll to my element

**Comment by feelthemoon** [comment]
> @feelthemoon can you share abit about it? I also work on nuxt 3, and nothing happens when I add v-dragscroll to my element

I just added a plugin in plugins directory, without it vue-dragscroll didn't work for me
