### ISSUE TITLE
Types export in package.json excluded

### ISSUE THREAD

**Issue by gitrojones** [donmbelembe/vue-dragscroll#113]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `vue-dragscroll@4.0.5` for the project I'm working on.

The way exports is setup for this package means types aren't a sibling of the dist export which means the specified types cannot be imported. This https://github.com/microsoft/TypeScript/issues/52363 post details the issue.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/vue-dragscroll/package.json b/node_modules/vue-dragscroll/package.json
index ed8c886..7967f86 100644
--- a/node_modules/vue-dragscroll/package.json
+++ b/node_modules/vue-dragscroll/package.json
@@ -9,7 +9,8 @@
   "exports": {
     ".": {
       "import": "./dist/vue-dragscroll.js",
-      "require": "./dist/vue-dragscroll.umd.cjs"
+      "require": "./dist/vue-dragscroll.umd.cjs",
+      "types": "./src/types.d.ts"
     }
   },
   "scripts": {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by donmbelembe** [comment]
updated
