### ISSUE TITLE
Click events inside directive not working on mobile

### ISSUE THREAD

**Issue by hazzo** [donmbelembe/vue-dragscroll#13]
Hi @donmbelembe,

Nice directive, it's wasn't working on mobile but I saw that you fixed in the las release. But now touch events of child elements won't work. It works on desktop but not in mobile.

Summary: If you bind a click event to the child elements will only trigger on desktop not mobile.

Cheers!

**Comment by donmbelembe** [comment]
Please provide example or screenshot

**Comment by donmbelembe** [comment]
Use `:nochilddrag` or attach event for now, I trying to figure out a solution for that

**Comment by hazzo** [comment]
Not a solution for me right now because the child elements are quite big and won't scroll if nochilddrag is set. 
If make some time I'll try to fix it.
Thanks!

**Comment by TheHugoBoss** [comment]
Well this isn't really a solution but a workaround. You can disable the dragscroll when touch device is detected.

Add something like this to your vue app:
`touchDevice: ('ontouchstart' in window || navigator.msMaxTouchPoints) || false`
And then add:
`v-dragscroll.x="!touchDevice"`

**Comment by kelnorris82** [comment]
> Well this isn't really a solution but a workaround. You can disable the dragscroll when touch device is detected.
> 
> Add something like this to your vue app:
> `touchDevice: ('ontouchstart' in window || navigator.msMaxTouchPoints) || false`
> And then add:
> `v-dragscroll.x="!touchDevice"`

Thanks TheHugoBoss... this worked for me

**Comment by kelnorris82** [comment]
> Use `:nochilddrag` or attach event for now, I trying to figure out a solution for that

What do you mean by 'attach an event'? can you give an example.

It would be great if we could 'disable' drag-scroll on individual child elements. I found that it disables certain events on other elements (specifically element.io focus events) which mean I can't use it in large parts of our site.

**Comment by donmbelembe** [comment]
that workaround will disable dragscrolling on touch device, so if your are unable to drag that mean you should find the issue in your own codes
@weijiahui1

**Comment by donmbelembe** [comment]
I just checked then if v-dragscroll is disabled and overflow is set to hidden then it will not be possible to drag by touch
@weijiahui1

**Comment by finnpham** [comment]
excuse me, but i read in this issue, the word around was fixed with alternative solution???
