### ISSUE TITLE
pass scroll when max reached

### ISSUE THREAD

**Issue by smbdelse** [donmbelembe/vue-dragscroll#14]
Hi

It would be helpful if scroll were passed to container, or further to the body, when max scroll position were reached, especially during one axis dragging.

on scrollable object I've added binding, like one showed in examples:
```
v-on:dragscrollmove="scrollMove($event.detail.deltaX, $event.detail.deltaY)"
```

And wrote small function:
```
      scrollMove: function(x, y){
        if (Math.abs(x) < Math.abs(y)) {
          window.scrollBy(0, y);
        }
      },
```

Unfortunately it cannot be done with scroll y disabled at same time.

**Comment by donmbelembe** [comment]
feature added
use _pass_ modifier in v1.7
commit  7ea91d43a4adf4732d9364f46ad42ead9f6cf4b0
