### ISSUE TITLE
Slow scroll stop

### ISSUE THREAD

**Issue by websanova** [donmbelembe/vue-dragscroll#16]
Add some kind of velocity factor for when dragging. So that it doesn't stop right away but slowly stops based on some "stopVelocity" factor and based on drag speed.

**Comment by rebz** [comment]
Anyone have a solution for this?

**Comment by donmbelembe** [comment]
pull request are welcome

**Comment by vin-ni** [comment]
I'd also be interested :)

**Comment by vin-ni** [comment]
I turned it off on mobile and got velocity from the browser
