### ISSUE TITLE
Events for manually controlling position.

### ISSUE THREAD

**Issue by websanova** [donmbelembe/vue-dragscroll#17]
Would be nice to manually change the x / y position, from something like a button. So for instance a left/right button, that then pan/slides it an x amount of pixels.

**Comment by donmbelembe** [comment]
I have another plugin for this [check the playgroundl](https://donmbelembe.github.io/vue-autoscroll/), unfortunately it doesn't support scroll to x amout of pixels but i was planning to do it. so if interested let me know I'll push a new release for vue-autoscroll

**Comment by websanova** [comment]
This one supports drag ? I don't see anything happening on mobile

**Comment by donmbelembe** [comment]
It doesn't support drag, I use it along with vue-gragscroll

**Comment by donmbelembe** [comment]
Open it on desktop to see well what I mean

**Comment by donmbelembe** [comment]
I've updated the doc for vue-autoscroll so you can view it better on mobile

**Comment by donmbelembe** [comment]
Feel free to reopen the issue if there is anything else
