### ISSUE TITLE
how can i use dragscroll only on x axis?

### ISSUE THREAD

**Issue by imsihyeong** [donmbelembe/vue-dragscroll#2]
plz help me

**Comment by donmbelembe** [comment]
make sure you child element height does not exceed the parent height. 
**CHILD HEIGHT <= PARENT HEIGHT**

**Comment by donmbelembe** [comment]
@imsihyeong I have publish a new version where you can just add a modifier to allow scrolling on axis.
check the documentation

**Comment by imsihyeong** [comment]
@donmbelembe thanks to your help, i have one question, my sources is
<div class="outer" v-dragscroll.x:nochilddrag>
  <div class="inner"></div>
</div>

inner width is large than outer
but height is small than outer
because v-dragscoll.x is not working
how can i use .x ??
