### ISSUE TITLE
How to get the drag distance between child elements

### ISSUE THREAD

**Issue by weijiahui1** [donmbelembe/vue-dragscroll#20]
中文：我想用vue-autoscroll和vue-dragscroll实现拖拽导航，并且可以点击左右按钮进行移动，我怎么实时获取到拖拽后的位置呢？
Englist： I want to use vue-autoscroll and vue-dragscroll to achieve drag-and-drop navigation, and can click the left and right buttons to move, how can I get the real-time position of the drag and drop?

**Comment by donmbelembe** [comment]
vue-dragscroll provide some [event](https://github.com/donmbelembe/vue-dragscroll#events) which you can use to get the scroll position.

You can see how it works by going to the [playgroung](https://donmbelembe.github.io/vue-dragscroll/) and look at you console while performing drag-scrolling

**Comment by donmbelembe** [comment]
Did it solve your question ? if not feel free to reopen the issue

**Comment by weijiahui1** [comment]
Thank you,This problem has not been solved yet. I would like to open my question.

At 2018-10-26 17:22:17, "donmbelembe" <notifications@github.com> wrote:


Did it solve your question ? if not feel free to reopen the issue

**Comment by donmbelembe** [comment]
Explain your issue well
