### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by HellDunkel** [donmbelembe/vue-dragscroll#22]
I sometimes get this in Firefox: 

TypeError: r.touches is undefined[Weitere Informationen] build.js line 1033 > eval:1:2437
o/e.mm
vue-dragscroll.min.js:1:2132

**Comment by donmbelembe** [comment]
which version of Firefox ?

**Comment by donmbelembe** [comment]
Everything seems to work on Firefox

**Comment by HellDunkel** [comment]
Sorry, I am not currently no longer able to reproduce the problem in Firefox. Nonetheless Rust (Mozillas experimental browser) comes up with a similar error:

ERROR 2018-10-27T20:37:02Z: script::dom::bindings::error: Error at http://localhost:3000/dist/build.js line 818 > eval:1:1589 n.touches is undefined

**Comment by donmbelembe** [comment]
Are you sure the problem is coming from this directive ?

**Comment by HellDunkel** [comment]
Here is what i found: My problem seems to be mainly rooted in Servo but i had Firefox Develop Edition also occasionally report an error (e.touches is undefined), however i cannot reproduce this.

When i looked at the code in directive.js i noticed that you check if e.pageX is undefined. if so you request e.touches[0].pageX but there is no check if this is undefined too. Can you please explain? I would really appreciate that.
