### ISSUE TITLE
Enable dragscroll on every child element except a certain one.

### ISSUE THREAD

**Issue by dhotlo2** [donmbelembe/vue-dragscroll#23]
I have tried v-dragscroll="false", :nochilddrag, :firstchilddrag, etc. 

My issue is that I have a parent element that I want to enable dragscroll on. I also want to allow dragscroll on its children and grandchildren. But down the tree, the last element is a card that has drag and drop functionality. For just these cards, I want to disable dragscrolling. I have no been able to achieve this at all.

**Comment by donmbelembe** [comment]
Right now the plugin does not support this feature

**Comment by dhotlo2** [comment]
> Right now the plugin does not support this feature

Is there a workaround that I can use to achieve this for the time being?
