### ISSUE TITLE
Links as drag content not working

### ISSUE THREAD

**Issue by bobby1212** [donmbelembe/vue-dragscroll#25]
If you try to use links as drag content, the links do not work because the event bubbeling is prevented by the directive. My solution for that is simply removing the `e.preventDefault()` from the start function.
What was the intention for this prevention and can this lead to unexpected behaviour?

**Comment by donmbelembe** [comment]
Please tell me what version of this directive you are using, because in the
latest version I solved that issue

**Comment by bobby1212** [comment]
Oh I was using v1.5.0...
Now i've updated and it works like a charm
Thank you and sorry that I annoyed you with an already solved issue ;)
