### ISSUE TITLE
No Scroll

### ISSUE THREAD

**Issue by movepixels** [donmbelembe/vue-dragscroll#27]
Just delete the question?

I have this:

```
<div v-dragscroll style="width:100%; height:90px; overflow:hidden" class="grab-bing">
   <p>Listen to your favorite artists and albums whenever and wherever, online and offline.
    Listen to your favorite artists and albums whenever and wherever, online and offline.
   </p>
.... paragraph above i pasted like 100 times but for sake of the question no need to include that
</div>
```
But nothing.

Please advise on what I am doing wrong?

**Comment by donmbelembe** [comment]
how did you installed it ? via npm or cdn ?

**Comment by donmbelembe** [comment]
I'm also getting this issue. but import inside component it works. so use it directly inside component until i fix the global import

`// Or, register it locally in a component
import { dragscroll } from 'vue-dragscroll'
export default {
  name: 'MyComponent',
  directives: {
    'dragscroll': dragscroll
  },
}`

**Comment by donmbelembe** [comment]
forget about the previous solution, actually i'm the one who made a mistake on the documentation.
it must be 
```
import VueDragscroll from 'vue-dragscroll'
Vue.use(VueDragscroll)
```

and not 
```
import VueDragscroll from 'vue-dragscroll'
Vue.directive(VueDragscroll)
```

please refer to the playground, i'm also updating the doc
https://donmbelembe.github.io/vue-dragscroll/

**Comment by movepixels** [comment]
Still no luck.
Followed your above reply.

My code for the scroll is:
```
<div v-dragscroll.x class="scroll filter-container grab-bing">
  <div v-for="filter in filters" :key="filter.name" class="filter-type">
    <h5 class="caption text-xs-center" :class="{'accent--text' : filter.value === record.class}">{{ filter.name }}</h5>
    <img @click="setFilter(filter.value)" class="img-responsive" :class="filter.value" :src="image.thumb" />
  </div>
</div>
```

But nothing? No scroll, no console errors.

Any ideas?

**Comment by donmbelembe** [comment]
is your console printing someting ?
check your console

**Comment by donmbelembe** [comment]
First all show me your file structure and in which file are you importing this
```
import VueDragscroll from 'vue-dragscroll'
Vue.use(VueDragscroll)
```

**Comment by movepixels** [comment]
This is a nuxt implementation so I created a plugin:
~/plugings/vue-dragscroll.js
```
import Vue from 'vue'
import VueDragscroll from 'vue-dragscroll'
Vue.use(VueDragscroll)
```

Imported that into nuxt.config:
```
{ src: '~/plugins/vue-dragscroll.js', ssr: false },
```
Even added / wrapped everything in a no-ssr tag to eliminate server side render
```
<no-ssr>
  <div v-dragscroll.x class="scroll filter-container grab-bing">
    <div v-for="filter in filters" :key="filter.name" class="filter-type">
      <h5 class="caption text-xs-center" :class="{'accent--text' : filter.value === record.class}">{{ filter.name }}</h5>
      <img @click="setFilter(filter.value)" class="img-responsive" :class="filter.value" :src="image.thumb" />
    </div>
  </div>
</no-ssr>
```

But still nothing.

Dave

**Comment by movepixels** [comment]
Console is clean. When I navigate or F5 hard refresh my console only has my axios requests which i have set to do. No errors or warning.

**Comment by movepixels** [comment]
These are the 2 styles being wrapped inside the v-dragscroll, not sure if that has anything to do with it but figured perhaps you see something I dont.
```
<style scoped>
  .filter-container {
    height: 130px;
    padding: 8px 4px;
    white-space: nowrap;
    overflow-x: hidden;
  }
  .filter-type {
  width: 75px;
  display: inline-block;
  margin: 0 5px;
}

.filter-type:last-child {
  margin-right: 20px;
}
</style>
```

**Comment by movepixels** [comment]
I have added that from the start:
```
plugins: [
    { src: '~/plugins/vue-dragscroll.js', ssr: false },
    ..... other plugings
  ],
```
Don't understand why its a no go.
Will try direct in component.

Any other suggestions? Does your plugin look like what I tried above in earlier post?

Thanks,
Dave

**Comment by donmbelembe** [comment]
yeah directly in component is better

**Comment by donmbelembe** [comment]
If you have team viewer I can help you out

**Comment by donmbelembe** [comment]
![index](https://user-images.githubusercontent.com/10473277/47951758-7d333900-df65-11e8-91e8-37ba9e113e73.PNG)
![plugin](https://user-images.githubusercontent.com/10473277/47951759-7dcbcf80-df65-11e8-9e96-3d036cc22889.PNG)
![config](https://user-images.githubusercontent.com/10473277/47951760-7dcbcf80-df65-11e8-8660-4a87743132ab.PNG)

**Comment by movepixels** [comment]
No team viewer. No idea what it is....lol

In my page CoverMgt.vue
```
import VueDragscroll from 'vue-dragscroll'
export default{
  name: 'CoverMgt',
  components: {
    VueDragscroll
  },
```

then the 
```
<no-ssr>
  <div v-dragscroll class="scroll filter-container grab-bing">
    <div v-for="filter in filters" :key="filter.name" class="filter-type">
      <h5 class="caption text-xs-center" :class="{'accent--text' : filter.value === record.class}">{{ filter.name }}</h5>
      <img @click="setFilter(filter.value)" class="img-responsive" :class="filter.value" :src="image.thumb" />
    </div>
  </div>
</no-ssr>
```

But still my div if thumbnails will not scroll.
![dragscroll-1](https://user-images.githubusercontent.com/1903217/47951781-67634b00-df48-11e8-94bb-af8fd9d2d791.png)

**Comment by movepixels** [comment]
Makes no sense. My plugin is exact as yours, imported the same.

**Comment by movepixels** [comment]
I tried it on another page and it works just fine. So it must be an issue on that page of thumbnails where something is going wacky. But I know the plugin is working as expected so I will try to solve why its not liking my thumbnails.

Thanks for your time and assistance. 
Appreciated!!

Dave

**Comment by donmbelembe** [comment]
To use inside CoverMgt.vue you should use it like this:
```
import { dragscroll } from 'vue-dragscroll'
export default {
  name: 'MyComponent',
  directives: {
    'dragscroll': dragscroll
  },
}
```

**Comment by movepixels** [comment]
Ok where I am at.
CoverMgt.vue:
```
<script>
import {mapState} from 'vuex'
import { dragscroll } from 'vue-dragscroll'
export default{
  name: 'CoverMgt',
  middleware: ['base'],
  directives: {
    'dragscroll': dragscroll
  }, ........
And the HTML bit....
```
<template>
  <div v-dragscroll class="grab-bing" style="height: 130px;padding: 8px 4px;overflow: hidden;white-space: nowrap;">
    <div v-for="filter in filters" :key="filter.name" class="filter-type">
      <h5 class="caption text-xs-center" :class="{'accent--text' : filter.value === record.class}">{{ filter.name }}</h5>
      <img @click="setFilter(filter.value)" class="img-responsive" :class="filter.value" :src="image.thumb" />
    </div>
  </div>
</template>
```

But same thing. No scroll, no errors. Hard force refresh. Clear cache. Restart server, re-run npm run dev. But can't get the scroll on these thumbnails to go.

**Comment by movepixels** [comment]
Stripped everything out and CoverMgt template now has 1 image only.
```
<div v-dragscroll class="grab-bing" style="height: 130px;padding: 8px 4px;overflow: hidden;">
   <img src="/img/dummy/placeholder.jpg"/>
</div>
```
The image shows in the mini area 130 x 100 container. sSame thing no scrollable, see top left corner of image but cant click and move it.
Tried massive text paragraphs, same thing. It hates this page.

**Comment by movepixels** [comment]
Ok Code is now:
```
<div v-dragscroll style="height: 130px;padding: 8px 4px;white-space: nowrap;overflow: hidden;">
   <img src="/img/dummy/placeholder.jpg"/>
</div>
```
No scroll.

Is the v-dragscroll or dragscroll? Since the directive is 'dragscroll'? Nit thinking of everything....

**Comment by donmbelembe** [comment]
I could give you free support if you had team viewer installed in your computer

**Comment by donmbelembe** [comment]
Try like this, see if you can scroll with scroll bar
<div v-dragscroll style="height: 130px;padding: 8px 4px;white-space: nowrap>
   <img src="/img/dummy/placeholder.jpg"/>
</div>

**Comment by movepixels** [comment]
I will install team viewer and post back once installed.

Thanks,

Dave

**Comment by movepixels** [comment]
Ok its installed. Username MovePixels

**Comment by movepixels** [comment]
Using:
```
<div v-dragscroll style="height: 130px;padding: 8px 4px;white-space: nowrap>
   <img src="/img/dummy/placeholder.jpg"/>
</div>
```
No scroll bars (x or y) Just the div and part of the image.

**Comment by movepixels** [comment]
```
<div v-dragscroll style="height: 130px;padding: 8px 4px;white-space: nowrap; overflow:auto">
```
Adding overflow:auto adds the y scrollbar standard browser scroll up and down.

**Comment by donmbelembe** [comment]
In other to display scroll bar you have to add overflow:auto ? it should be the default behavior try to see maybe an issue with your css

**Comment by movepixels** [comment]
I have it working now. For some reason it will not work if I have another component on the same page. I dont know why this is happening but if i put your component on a page with this other component:
https://github.com/NightCatSama/vue-slider-component

it will not work. Both have nothing to do with each other, no shared anything. No errors, no console issues, they just dont seem to want to play together.

**Comment by movepixels** [comment]
I have my dashboardMgt.vue with many many components and thru process of elimination when I removed the components one at a time until your worked. The one that used the vue-slider component above, when commented out only then yours worked no problem. So now to see why this is happening.

**Comment by movepixels** [comment]
Both work in this fiddle:

Odd

```https://jsfiddle.net/1apr0wg4/
```
