### ISSUE TITLE
thanks to your help 

### ISSUE THREAD

**Issue by imsihyeong** [donmbelembe/vue-dragscroll#3]
@donmbelembe thanks to your help, i have one question, my sources is

```
<div class="outer" v-dragscroll.x:nochilddrag>
  <div class="inner"></div>
</div>
```
inner width is large than outer
but height is small than outer
because v-dragscoll.x is not working
how can i use .x ??

**Comment by donmbelembe** [comment]
with the `:nochilddrag`, it means the drag-scrolling will work only if you click directly on the outer element. So remove it and see. check the first issue maybe you will undestand

**Comment by donmbelembe** [comment]
https://github.com/donmbelembe/vue-dragscroll/issues/1

**Comment by donmbelembe** [comment]
also the axis modifier is available only on the version 1.2 that i have published yesterday. so update the version on your project if not yet

**Comment by imsihyeong** [comment]
i removed :nochilddrag, but also not working only on x axis

**Comment by donmbelembe** [comment]
Please Share code on codepen

**Comment by imsihyeong** [comment]
thank you, i resolved the issue by updating version
