### ISSUE TITLE
Chrome Message : Added non-passive event listener to a scroll-blocking <some> event.

### ISSUE THREAD

**Issue by vomnes** [donmbelembe/vue-dragscroll#33]
Are there something simple to do to remove this 'Verbose' message on Google Chrome : `[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

**Comment by donmbelembe** [comment]
Please be specific what is your issue
