### ISSUE TITLE
scroll-behavior: smooth; - Not compatible

### ISSUE THREAD

**Issue by tophat1986** [donmbelembe/vue-dragscroll#35]
Unfortunately it doesn't appear to be compatible with this CSS property:
`scroll-behavior: smooth;`

I'm using this because I have child div's that are selected from buttons that will scrollLeft() in the container to show child div in central position.

**Comment by aacoelho** [comment]
I applied the scrollLeft like this and the smooth effect works.

```
element.scrollTo({
  behavior: "smooth",
  left: 0
});
```
