### ISSUE TITLE
textarea and input change text not working

### ISSUE THREAD

**Issue by sokolovdm** [donmbelembe/vue-dragscroll#36]
Hi!
I have an issue with textarea and input inside v-dragscroll element - adding and deleting text does not work.

**Comment by donmbelembe** [comment]
Can you provide a sample so I can reproduce the error

**Comment by sokolovdm** [comment]
https://codepen.io/naraxiss/pen/xMjwqX

**Comment by donmbelembe** [comment]
Please use the latest version (1.8.2)

**Comment by sokolovdm** [comment]
Great work! 
Thank you.
