### ISSUE TITLE
focus on input/textarea set cursor to end

### ISSUE THREAD

**Issue by sokolovdm** [donmbelembe/vue-dragscroll#37]
Thanks for your last hot fix, but now focus setting only to end input/textarea

**Comment by donmbelembe** [comment]
I did not get exactly your point, can you give more explanation ?

**Comment by sokolovdm** [comment]
Dragscroll OFF
![normal](https://user-images.githubusercontent.com/29097652/52689877-d0f1ed00-2f6c-11e9-94c0-7c4fb21da174.gif)

Dragscroll ON
![not normal](https://user-images.githubusercontent.com/29097652/52689987-3fcf4600-2f6d-11e9-9ef0-f5e46c975544.gif)

**Comment by donmbelembe** [comment]
please try version 2.0 and let me know if the issue persist
