### ISSUE TITLE
Not compatible with vuedraggable

### ISSUE THREAD

**Issue by henkm** [donmbelembe/vue-dragscroll#41]
In my interface I already have draggable components with the vuedraggable library. Whenever I add the dragscroll directive to a parent element, the draggable components stop working.

Is this intended behaviour? Is there a way around it?

**Comment by romancm** [comment]
+1

**Comment by donmbelembe** [comment]
> In my interface I already have draggable components with the vuedraggable library. Whenever I add the dragscroll directive to a parent element, the draggable components stop working.
> 
> Is this intended behaviour? Is there a way around it?

Hello sir, sorry i'm too late, it would be better if you provided an example along with you question so that we can find a solution, 
the draggable element are inside the dragscroll element ?

**Comment by kshitizshankar** [comment]
Trying to do something similar - 
Use Case - Trello Board.

I have a board which contains Lists (which are draggable) and List contains cards (which are draggable). Am trying to enable DragScroll on the top container element to be able to scroll the board horizontally.

Any suggestions?

**Comment by Tofandel** [comment]
My two cent:
Having a dragable inside of a dragscroll is not easy to use and doesn't make real sense for a user

I would use a scroll on hover border in that case instead of a draggable scroll

**Comment by donmbelembe** [comment]
please try version 2.0 and let me know if the issue persist

**Comment by Neophen** [comment]
Hey the issue persist with version 2.0
Did anyone you manage to solve that?
