### ISSUE TITLE
How to disable scrolling of the main content?

### ISSUE THREAD

**Issue by madeas** [donmbelembe/vue-dragscroll#46]
How can I disabled scrolling main content through the "Y" axis while I am scrolling through the "X" axis?

sample https://jsfiddle.net/madeas/gtu5rn8e/

**Comment by donmbelembe** [comment]
In your example you used the v-dragscroll directive twice. in the main content and in the slider. is it a mistake ?

**Comment by madeas** [comment]
Not.
I scroll the content vertically with the mouse. Slides are spinning horizontally. The problem is that when I move the slides, the main content also moves... This does not look good for UI.

**Comment by donmbelembe** [comment]
Sorry for late answer,
did you try to use `data-dragscroll` directive ? _(have a look at the docs)_

here is an update that I've made to your example but you can refactor your code to avoid some repetition
https://jsfiddle.net/6hqg0rdu/

**Comment by madeas** [comment]
You do not have a directive in which, when the child hits the target, the parent stops scrolling?

**Comment by donmbelembe** [comment]
No

**Comment by madeas** [comment]
Ok, maybe is it possible to somehow disable the scroll content on click? 
Exaple:

```
childrenBlock.addEventListener('mousemove', function () {
	globalContent.setAttribute ('v-dragscroll.y', 'false')
});
```
