### ISSUE TITLE
Get Offset

### ISSUE THREAD

**Issue by weilbith** [donmbelembe/vue-dragscroll#5]
I wanna ask if it is possible to get the offset of the x- and y-axis by which the content is shifted in the container?
The idea behind is, to let the user drag the image in a fix container, till it fits. Afterwards I wanna store this configuration to make it persistent. 
Thanks for any help. :)

**Comment by donmbelembe** [comment]
try to listen to the scroll event on the container,
you store first the initial position then after the scroll event you get the new position and compare to the initial.

If you think it should be included in the plugin please provide some reasons.

**Comment by weilbith** [comment]
Think try to use this as solution was the false approach. I implemented it on my own with vue-dragged.
