### ISSUE TITLE
vue dynamic templates

### ISSUE THREAD

**Issue by madeas** [donmbelembe/vue-dragscroll#53]
1. Please tell me, "v-dragscroll.y='true'" does not work for templates in dynamic components? **template: ``** and (v-dragscroll="{ target: '.pr-container' }") does not work.

2. When connecting "v-dragscroll.y" property css "scroll-behavior: smooth;" does not work. can this be fixed somehow?

**Comment by Xationch** [comment]
@madeas Can you share the solution for the number 2 ?
