### ISSUE TITLE
errors on ipad

### ISSUE THREAD

**Issue by jappyjan** [donmbelembe/vue-dragscroll#55]
When using an iPad i receive "e.target.click" is not a function errors when dragging.

this error is caused in line 97 of directive.js.

i guess you need to implement a check if target is available and has the click property.

by now i didn't had the time to further investigate the problem.

**Comment by jappyjan** [comment]
the original error:

`TypeError: t.target.click is not a function. (In 't.target.click()', 't.target.click' is undefined)
  at options(./node_modules/vue-dragscroll/dist/vue-dragscroll.min.js:1:3332)
  at r(./node_modules/@sentry/browser/esm/helpers.js:82:25)`

**Comment by jappyjan** [comment]
anyone reading this?

**Comment by donmbelembe** [comment]
please try version 2.0 and let me know if the issue persist
