### ISSUE TITLE
vue-dragscroll + zoom on mobile

### ISSUE THREAD

**Issue by hvilppu** [donmbelembe/vue-dragscroll#56]
I got problems.

I make default "pinch" zoom on my page. Then I move middle of picture with vue-dragscroll.. Then  I ran in problems:
1) I lost mobile "pinch" zoom (Is there way to get it work on vue-dragscrol div?)
2) I can  not "pan scroll" page on  "vue-dragscroll div" so my screen is "locked" middle of picture

Any help for this on?

**Comment by donmbelembe** [comment]
please try to reproduce the issue and share with me the code

**Comment by PuKoren** [comment]
The code on the page https://donmbelembe.github.io/vue-dragscroll/ have the issue. 

It's impossible to zoom using the pinch of mobiles on a section under dragscroll control. Could confirm on iPhone SE 2.
For images, its a bit confusing for users as they are used to zoom with gestures
