### ISSUE TITLE
Not usable on Nuxt - 'window is not defined'

### ISSUE THREAD

**Issue by PayteR** [donmbelembe/vue-dragscroll#58]
Hi, this plugin is not usable on Nuxt anymore due to fact, that page is generated on server first (Node.js) and there is no `window` object.  Please don't call `window` object, or check if it's not undefined first. Thx.

![image](https://user-images.githubusercontent.com/1248565/71306746-aa9aaa80-23e4-11ea-859d-c50460e0e0ca.png)

**Comment by alijaya** [comment]
I have the same issue ._. I'm using gridsome though

**Comment by donmbelembe** [comment]
I'm using the window object multiple places, this plugin is intended to be rendered on client client, please set SSR to false on your nuxt.config.js file

plugins: [
    { src: '~/plugins/vue-dragscroll', ssr: false }
 ]
