### ISSUE TITLE
Applying directive causes select (drop down menus) elements to become broken

### ISSUE THREAD

**Issue by kchow1985** [donmbelembe/vue-dragscroll#59]
When applying the `v-dragscroll` directive, any `<select>` element that is nested within the element with the v-dragscroll cease to show the menu upon clicking.

I tried to use `data-no-dragscroll` directive right on the select element itself but that does not fix the issue.

Not sure for the other browsers, but this is happening on Chrome (using Electron)

**Comment by donmbelembe** [comment]
please try version 2.0 and let me know if the issue persist
