### ISSUE TITLE
Emitting events

### ISSUE THREAD

**Issue by celeryclub** [donmbelembe/vue-dragscroll#6]
Hi there. Thanks for creating this plugin! I have a feature suggestion. I think it would be nice to emit a simple drag start/end event (and potentially a drag move event as well) on the relevant element. In the project I'm using this for it would be helpful to know when the dragging stops in order to re-enable certain behaviors. I'm happy to open a PR myself if you think this is a good idea.

**Comment by donmbelembe** [comment]
Yes I think it's a good idea. please submit your PR.

**Comment by celeryclub** [comment]
Thanks @donmbelembe. I've opened the PR.
