### ISSUE TITLE
vue-dragscroll + vue-draggable

### ISSUE THREAD

**Issue by jhasuev** [donmbelembe/vue-dragscroll#63]
http://prntscr.com/qweiin

Hi! I have a problem with combine these two plugins.

When I use vue-dragscroll, vue-draggable stopping work. 

I think vue-dragscroll blocks any other click events and disallows to work vue-draggable correctly.

How can I to stop blocking click/touch events in all child elements? 
:nochilddrag doesn't help.

**Comment by donmbelembe** [comment]
please try version 2.0 and let me know if the issue persist

**Comment by Neophen** [comment]
Hey the issue persist with version 2.0
