### ISSUE TITLE
Ctrl-click or right-click starts dragging

### ISSUE THREAD

**Issue by mattgilbertnet** [donmbelembe/vue-dragscroll#82]
When I ctrl-click or right-click in a draggable area, then click outside the options menu to leave it, the area acts as if I've started dragging it, even though the mouse is not being pressed.

Is this a bug or expected behavior? Is there a way to ensure vue-dragscroll ignores ctrl-click or right-click events?

This issue can be reproduced using this CodePen:
https://codepen.io/itslit/pen/EEBYGa

Here's a screen recording of the issue. Note that I clicked outside of the options menu, and was not dragging when the background is following my mouse.

https://user-images.githubusercontent.com/1780943/112762251-a8060800-8fcc-11eb-80ce-a49f0cbde57e.mp4

**Comment by donmbelembe** [comment]
Thank you for reporting this, this is not the expected behaviour I'll have a look at that

**Comment by donmbelembe** [comment]
Close since I can't reproduce the same issue, even the pen provided
