### ISSUE TITLE
Documentation for Global Implementation does not work

### ISSUE THREAD

**Issue by rebz** [donmbelembe/vue-dragscroll#9]
Tried the following below but failed to work.
`import dragscroll from 'vue-dragscroll'`

Used the following and it worked.
`import { dragscroll } from 'vue-dragscroll'`

Sorry, didn't setup a online example. If you are unable to replicate I may create one later. Just wanted to document.

**Comment by donmbelembe** [comment]
what is the current version you are using

**Comment by donmbelembe** [comment]
Actually When you are using the vue-cli then only you can import like that after installing using npm.

inside src/main.js _(to install globally)_

import dragscroll from 'vue-dragscroll'
Vue.directive('dragscroll', dragscroll)

or inside src/components/MyComponent.vue _(To install locally on a component)_
