### ISSUE TITLE
[Feature request] Scroll one direction at a time

### ISSUE THREAD

**Issue by PixsaOJ** [donmbelembe/vue-dragscroll#91]
It would be nice if user could scroll in one direction at a time instead of free panning.

For example, I had to use dragscroll with pass to make this work on mobile. I wanted to skip the slider but also able to horizontally scroll it. Now, when I scroll down but slightly move my finger left, it looks bad, content freaks out. Maybe we could have a moving treshold as an alternative?

**Comment by donmbelembe** [comment]
Yes, please feel free to send a PR
